// Shared types & helpers used across the whole site.
// Board data modules import from here. Do NOT edit this file in board agents.

export type Locale = "en" | "zh";
export const LOCALES: Locale[] = ["en", "zh"];

/** Bilingual text. Both languages should be filled. */
export interface LocalizedText {
  en: string;
  zh: string;
}

/** Return the string for the active locale (falls back to en). */
export function localize(text: LocalizedText, locale: Locale): string {
  return text[locale] ?? text.en;
}

export type AccentColor = "cyan" | "magenta" | "violet" | "lime" | "amber";

/** Hex values per accent — used to drive the `--accent` CSS custom property. */
export const ACCENT_HEX: Record<AccentColor, string> = {
  cyan: "#00e5ff",
  magenta: "#ff2d95",
  violet: "#b14bff",
  lime: "#adff2f",
  amber: "#ffb347",
};

export type AspectRatio = "16/9" | "4/3" | "1/1" | "3/4" | "21/9";

/** A programmatic placeholder image (zero copyright risk). */
export interface MediaPlaceholder {
  kind: "placeholder";
  label: LocalizedText;
  /** Deterministic seed for the generated pattern; a slug works well. */
  seed: string;
  aspect?: AspectRatio;
  accent?: AccentColor;
  /** Optional lucide icon name rendered on the placeholder. */
  icon?: string;
}

/** A referenced YouTube video. `videoId` may be "" → component degrades to a placeholder. */
export interface YouTubeRef {
  kind: "youtube";
  videoId: string;
  title: LocalizedText;
}

export type Media = MediaPlaceholder | YouTubeRef;

/** Type guard */
export function isYouTube(media: Media): media is YouTubeRef {
  return media.kind === "youtube";
}
